C:\Users\admin\Desktop\realtech-blogx\backend\cms\realtech_blogx\settings.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /cms-api/v1/posts/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\realtech_blogx\settings.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /cms-api/v1/posts/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /auth/token/logout/
Bad Request: /cms-api/v1/posts/
Not Found: /favicon.ico
Internal Server Error: /schema/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 206, in parse
    endpoints = self._get_paths_and_endpoints()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 196, in _get_paths_and_endpoints
    view = self.create_view(callback, method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 147, in create_view
    action = getattr(view, view.action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CommentViewSet' object has no attribute 'reject'
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /schema/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 206, in parse
    endpoints = self._get_paths_and_endpoints()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 196, in _get_paths_and_endpoints
    view = self.create_view(callback, method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 147, in create_view
    action = getattr(view, view.action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NotificationViewSet' object has no attribute 'mark_all_as_read'. Did you mean: 'mark_as_read'?
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /schema/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 206, in parse
    endpoints = self._get_paths_and_endpoints()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 196, in _get_paths_and_endpoints
    view = self.create_view(callback, method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\drf_spectacular\generators.py", line 147, in create_view
    action = getattr(view, view.action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CommentViewSet' object has no attribute 'for_post'
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Bad Request: /auth/token/logout/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /cms-api/v1/posts/
Bad Request: /cms-api/v1/posts/
Bad Request: /cms-api/v1/posts/
Bad Request: /cms-api/v1/posts/
Bad Request: /cms-api/v1/posts/
Bad Request: /cms-api/v1/posts/
Unauthorized: /cms-api/v1/posts/
Unauthorized: /cms-api/v1/posts/
Bad Request: /auth/token/logout/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\serializers.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /cms-api/v1/posts/
Bad Request: /auth/token/logout/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /cms-api/v1/posts/
Bad Request: /cms-api/v1/posts/
Unauthorized: /cms-api/v1/posts/
Bad Request: /auth/token/logout/
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Bad Request: /auth/token/logout/
Bad Request: /auth/token/logout/
Bad Request: /auth/token/logout/
Bad Request: /auth/token/logout/
Bad Request: /auth/token/logout/
Bad Request: /auth/token/logout/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /auth/token/logout/
Not Found: /cms-api/v1/posts/why-go-is-gaining-momentum-in-backend-development/
Not Found: /cms-api/v1/posts/why-go-is-gaining-momentum-in-backend-development/
Not Found: /cms-api/v1/posts/why-go-is-gaining-momentum-in-backend-development/
Not Found: /cms-api/v1/posts/why-go-is-gaining-momentum-in-backend-development/
